### ISSUE TITLE
np.concatenate((cur_polyline[:, 0:3], cur_polyline[:, 3:]), axis=-1) appears redundant

### ISSUE THREAD

**Issue by hzxie** [rainmaker22/SMART#18]
It appears that the code `cur_polyline = np.concatenate((cur_polyline[:, 0:3], cur_polyline[:, 3:]), axis=-1)` may not be necessary, as it seems to be reassembling `cur_polyline` without making any changes.

https://github.com/rainmaker22/SMART/blob/55947594ed2e499010cfc03a5d3d45e128ab3ec4/data_preprocess.py#L535

https://github.com/rainmaker22/SMART/blob/55947594ed2e499010cfc03a5d3d45e128ab3ec4/data_preprocess.py#L547

https://github.com/rainmaker22/SMART/blob/55947594ed2e499010cfc03a5d3d45e128ab3ec4/data_preprocess.py#L558

https://github.com/rainmaker22/SMART/blob/55947594ed2e499010cfc03a5d3d45e128ab3ec4/data_preprocess.py#L579

https://github.com/rainmaker22/SMART/blob/55947594ed2e499010cfc03a5d3d45e128ab3ec4/data_preprocess.py#L588

**Comment by OrangeSodahub** [comment]
So what does that matter?

**Comment by hzxie** [comment]
Nothing affects. But makes me confused.

**Comment by rainmaker22** [comment]
Please disregard this part. Initially, cur_polyline had many features, and we removed some unnecessary ones by indexing and concatenation. However, due to later code modifications, the indices used for concatenation changed, so this approach no longer serves a purpose.

**Comment by hzxie** [comment]
I see. Thanks for your reply.
