### ISSUE TITLE
Error in validation phase in training

### ISSUE THREAD

**Issue by zachytong** [rainmaker22/SMART#5]
Hi rainmaker22,

I came across an error as follow

> lightning_fabric.utilities.exceptions.MisconfigurationException: `ModelCheckpoint(monitor='val_cls_acc')` could not find the monitored key in the returned metrics: ['train_loss', 'train_loss_step', 'cls_loss', 'cls_loss_step', 'val_loss', 'train_loss_epoch', 'cls_loss_epoch', 'epoch', 'step']. HINT: Did you call `log('val_cls_acc', value)` in the `LightningModule`?` .

It seems that this is caused by val_cls_acc not logged with inference_token set to False in smart.py. Setting it to True or tracking another metrics/loss will work fine. Not sure which one is better, maybe you can help: )

**Comment by rainmaker22** [comment]
Thank you for bringing up this issue. I've submitted a commit to fix the error. Apologies for mistakenly removing the val_cls_acc log earlier. Due to time constraints, the code might not have been thoroughly tested. If you encounter any further issues, feel free to let me know.
