### ISSUE TITLE
Code for K-disk?

### ISSUE THREAD

**Issue by pengzhenghao** [rainmaker22/SMART#6]
Hi, thanks for open sourcing this project!

I wonder will you release (or if already please point to me) the code to do clustering on the dataset to generate: [cluster_frame_5_2048.pkl](https://github.com/rainmaker22/SMART/blob/main/smart/tokens/cluster_frame_5_2048.pkl) ?

I want to know how you generate this file. I believe you use the same K-disk algorithm like Trajglish. Thanks!

**Comment by OrangeSodahub** [comment]
@rainmaker22 Same question thanks!

**Comment by rainmaker22** [comment]
OK, we will upload the code.

**Comment by ziyanGao** [comment]
We have added a clustering algorithm in scripts/traj_clustering.py. Please note that the input trajectory data must be collected from the raw data independently.

**Comment by OrangeSodahub** [comment]
@ziyanGao Hi, thanks for the codes. Did you provided the complete codes for generating the token files? namely `tokens/map_traj_token5.pkl` and `tokens/cluster_frame_5_2048.pkl`? I was wondering how to produce them

**Comment by pengzhenghao** [comment]
Thank you for providing the examplar script for K-disk. I can make the clustering by myself. I won't close the issue though as the community seems to be interested in more out-of-box clusters.

**Comment by pengzhenghao** [comment]
@ziyanGao Would you mind discussing what is the ret_traj? Can I unstand that a `ret_traj` is a little polyline that shows the chunk of trajectory in `5 steps`, corresponding to the cluster?

**Comment by rainmaker22** [comment]
> @ziyanGao Would you mind discussing what is the ret_traj? Can I unstand that a `ret_traj` is a little polyline that shows the chunk of trajectory in `5 steps`, corresponding to the cluster?

Yes, that's correct. We cluster only the final step of the trajectory using k-disk. The first 5 steps are derived by averaging the trajectories surrounding the sampled token within the k-disk algorithm.

**Comment by pengzhenghao** [comment]
Thanks for the reply! A follow-up question is are u creating only one code book for trajectories of all 3 types of agents? Or are u use 3 codebooks and when do the postprocessing you interpret the predicted trajectory according to the agent type? Thanks!

**Comment by rainmaker22** [comment]
> Thanks for the reply! A follow-up question is are u creating only one code book for trajectories of all 3 types of agents? Or are u use 3 codebooks and when do the postprocessing you interpret the predicted trajectory according to the agent type? Thanks!

We use three separate codebooks for the different agent types, but it's also possible to combine them into a single, larger codebook with additional tokens.

**Comment by pengzhenghao** [comment]
@rainmaker22 Thanks for the information. So how you use different codebooks in decoding? Are u using 3 different prediction heads that transform the transformer's output into the token distributions? Or you just simply use the same prediction head but "inteprete" the sampled token from different codebooks according to the agent type?

**Comment by pengzhenghao** [comment]
Another question here is the code:

https://github.com/rainmaker22/SMART/blob/main/scripts/traj_clstering.py#L25C9-L25C65

`np.sum((X - x0)**2, axis=(1, 2))/4 > (tol**2)`

seems not having any physical meaning? The sum of squares is not a distance metric (neither the square of a distance metric). Will this affeact a lot?

**Comment by rainmaker22** [comment]
This code is used to filter out candidate tokens that are too close to the current token. We calculate the squared distances of the four corners of the rectangle. If you want to give it more physical meaning, you could take the square root before summing along axis=1 and dividing by 4. However, I don't think this affeact a lot, as the specific tol threshold is tuned through multiple tests.

**Comment by pengzhenghao** [comment]
Thanks for the information! When I implementing the code I find the computing efficiency is extremely slow as the number of tokens, even only for vehicle, can reach the 1e8 order of magnitude for waymo training set. How you guys solve this?

**Comment by rainmaker22** [comment]
> Thanks for the information! When I implementing the code I find the computing efficiency is extremely slow as the number of tokens, even only for vehicle, can reach the 1e8 order of magnitude for waymo training set. How you guys solve this?

You can sample the tokens randomly, we don't need too many tokens for K-disk, 1e6 tokens are enough.
