### ISSUE TITLE
`shifts=-2` instead of `shifts=-1` in inference mode

### ISSUE THREAD

**Issue by OrangeSodahub** [rainmaker22/SMART#8]
Since you predict only last 16 tokens of total 18 tokens, then the first 2 should be discarded. So here should be `shifts=-2` instead of `shifts=-1` ?

https://github.com/rainmaker22/SMART/blob/69c7a419d5004a762ffd3305ebda4e055bd7a0db/smart/modules/agent_decoder.py#L505

If I was wrong, please point out, thanks!

**Comment by pengzhenghao** [comment]
I think they are just meaning that this is simply a next token prediction task so all tokens[1:] will be the GT output of the tokens[:-1]?

**Comment by rainmaker22** [comment]
> I think they are just meaning that this is simply a next token prediction task so all tokens[1:] will be the GT output of the tokens[:-1]?

That's correct.

**Comment by OrangeSodahub** [comment]
Thanks, before I noticed the `next_token_idx_gt` mentioned above is used here:

https://github.com/rainmaker22/SMART/blob/69c7a419d5004a762ffd3305ebda4e055bd7a0db/smart/model/smart.py#L184

**Comment by OrangeSodahub** [comment]
I still think here shouldn't be `shifts=-1`:

https://github.com/rainmaker22/SMART/blob/69c7a419d5004a762ffd3305ebda4e055bd7a0db/smart/modules/agent_decoder.py#L505

Note that the line is under `inference` mode, not training mode, well in training code, do `shifts=-1` makes sense:

https://github.com/rainmaker22/SMART/blob/69c7a419d5004a762ffd3305ebda4e055bd7a0db/smart/modules/agent_decoder.py#L339

@rainmaker22 Thanks!
